package database

import (
	"basic/models"
)

// AdminSettingInit 初始化管理配置
func AdminSettingInit() []*models.AdminSetting {
	return []*models.AdminSetting{
		{AdminId: 1, GroupId: models.AdminSettingGroupBasic, Name: "站点名称", Type: models.AdminSettingTypeText, Field: "siteName", Value: "BaJie"},
		{AdminId: 1, GroupId: models.AdminSettingGroupBasic, Name: "站点Logo", Type: models.AdminSettingTypeImage, Field: "siteLogo", Value: ""},
		{AdminId: 1, GroupId: models.AdminSettingGroupBasic, Name: "站点介绍", Type: models.AdminSettingTypeTranslate, Field: "siteIntroduce", Value: "introduce"},
		{AdminId: 1, GroupId: models.AdminSettingGroupBasic, Name: "站点公告", Type: models.AdminSettingTypeTranslate, Field: "siteAnnouncement", Value: "announcement"},
		{AdminId: 1, GroupId: models.AdminSettingGroupBasic, Name: "轮播图", Type: models.AdminSettingTypeImages, Field: "siteBanners", Value: `["/assets/banner/banner1.png", "/assets/banner/banner2.png", "/assets/banner/banner3.png", "/assets/banner/banner4.png"]`},
		{AdminId: 1, GroupId: models.AdminSettingGroupBasic, Name: "客服链接", Type: models.AdminSettingTypeText, Field: "onlineLink", Value: ""},
		{AdminId: 1, GroupId: models.AdminSettingGroupBasic, Name: "客服图标", Type: models.AdminSettingTypeImage, Field: "onlineImage", Value: "/assets/icon/online.png"},
		{AdminId: 1, GroupId: models.AdminSettingGroupBasic, Name: "社区账号", Type: models.AdminSettingTypeChildren, Field: "socialList", Value: `[{"icon": "/assets/icon/telegram.png", "name": "Telegram", "link": "https://t.me/bajie119", "status": 10}, {"icon": "/assets/icon/facebook.png", "name": "Facebook", "link": "", "status": 10}, {"icon": "/assets/icon/whatsapp.png", "name": "Whatsapp", "link": "", "status": 10}, {"icon": "/assets/icon/line.png", "name": "Line", "link": "", "status": 10}, {"icon": "/assets/icon/twitter.png", "name": "Twitter", "link": "", "status": 10}]`, Data: `[[{"label": "图标", "field": "icon", "type": 22}],[{"label": "名称", "field": "name", "type": 1}, {"label": "链接", "field": "link", "type": 1}, {"label": "状态", "field": "status", "type": 10, "data": [{"label": "开启", "value": 10}, {"label": "关闭", "value": -1}]}]]`},
		{AdminId: 1, GroupId: models.AdminSettingGroupBasic, Name: "联系我们", Type: models.AdminSettingTypeChildren, Field: "contactList", Value: `[{"icon": "place", "name": "607-699 14th Pl NE, Washington, DC 20002 USA", "link": "https://maps.app.goo.gl/U2gNxExtu16Tbasb8", "status": 10}, {"icon": "phone_iphone", "name": "+12023883500", "link": "tel:12023883500", "status": 10}, {"icon": "forward_to_inbox", "name": "muiprosperyls15@gmail.com", "link": "mailto:muiprosperyls15@gmail.com", "status": 10}]`, Data: `[[{"label": "图标", "field": "icon", "type": 22}],[{"label": "名称", "field": "name", "type": 1}, {"label": "链接", "field": "link", "type": 1}, {"label": "状态", "field": "status", "type": 10, "data": [{"label": "开启", "value": 10}, {"label": "关闭", "value": -1}]}]]`},
		{AdminId: 1, GroupId: models.AdminSettingGroupBasic, Name: "软件下载", Type: models.AdminSettingTypeJson, Field: "download", Value: `{"android": "", "ios": ""}`, Data: `[[{"label": "安卓包地址", "field": "android", "type": 21}, {"label": "苹果包地址", "field": "ios", "type": 21}]]`},
		{AdminId: 1, GroupId: models.AdminSettingGroupBasic, Name: "等级购买模式", Type: models.AdminSettingTypeSelect, Field: "buyLevelMode", Value: "1", Data: `[{"label": "补价购买", "value": 1}, {"label": "等额购买", "value": 2}]`},
		{AdminId: 1, GroupId: models.AdminSettingGroupBasic, Name: "提示音设置", Type: models.AdminSettingTypeCheckbox, Field: "audioSetting", Value: `{"deposit": false, "withdraw": false}`, Data: `[{"label": "充值", "value": "deposit"}, {"label": "提现", "value": "withdraw"}]`},

		{AdminId: 1, GroupId: models.AdminSettingGroupWallet, Name: "绑定卡片类型数量", Type: models.AdminSettingTypeNumber, Field: "walletAccountNums", Value: "5"},
		{AdminId: 1, GroupId: models.AdminSettingGroupWallet, Name: "充值金额范围", Type: models.AdminSettingTypeJson, Field: "walletDepositAmountBetween", Value: `{"min": 100, "max": 999999}`, Data: `[[{"label": "最小金额", "field": "min", "type": 4}, {"label": "最大金额", "field": "max", "type": 4}]]`},
		{AdminId: 1, GroupId: models.AdminSettingGroupWallet, Name: "充值注意事项提示", Type: models.AdminSettingTypeTranslate, Field: "walletDepositDesc", Value: "depositDesc"},
		{AdminId: 1, GroupId: models.AdminSettingGroupWallet, Name: "提现金额范围", Type: models.AdminSettingTypeJson, Field: "walletWithdrawAmountBetween", Value: `{"min": 100, "max": 999999}`, Data: `[[{"label": "最小金额", "field": "min", "type": 4}, {"label": "最大金额", "field": "max", "type": 4}]]`},
		{AdminId: 1, GroupId: models.AdminSettingGroupWallet, Name: "提现配置", Type: models.AdminSettingTypeJson, Field: "walletWithdrawSetting", Value: `{"day": 7, "nums": 7, "fee": 0}`, Data: `[[{"label": "天数", "field": "day", "type": 4}, {"label": "次数", "field": "nums", "type": 4}, {"label": "手续费", "field": "fee", "type": 4}]]`},
		{AdminId: 1, GroupId: models.AdminSettingGroupWallet, Name: "提现注意事项提示", Type: models.AdminSettingTypeTranslate, Field: "walletWithdrawDesc", Value: "withdrawDesc"},

		{AdminId: 1, GroupId: models.AdminSettingGroupEarnings, Name: "注册邀请奖励", Type: models.AdminSettingTypeJson, Field: "registerAward", Value: `{"register": 0, "share": 0}`, Data: `[[{"label": "注册奖励", "field": "register", "type": 4}, {"label": "邀请奖励", "field": "share", "type": 4}]]`},
		{AdminId: 1, GroupId: models.AdminSettingGroupEarnings, Name: "分销配置(第一条数据为 1Lv ...类推)", Type: models.AdminSettingTypeChildren, Field: "earningsSetting", Value: `[{"options": {}, "rate": 50}, {"options": {}, "rate": 30}, {"options": {"walletBillTypeBuyProduct": false, "walletBillTypeAssetsBuyProduct": false, "walletBillTypeEarnings": false, "walletBillTypeAssetsEarnings": false}, "rate": 10}]`, Data: `[[{"label": "操作", "field": "options", "type": 12, "data": [{"label": "账户购买产品", "value": "walletBillTypeBuyProduct"}, {"label": "资产购买产品", "value": "walletBillTypeAssetsBuyProduct"}, {"label": "账户收益", "value": "walletBillTypeEarnings"}, {"label": "资产收益", "value": "walletBillTypeAssetsEarnings"}]}, {"label": "收益率", "field": "rate", "type": 4}]]`},

		{AdminId: 1, GroupId: models.AdminSettingGroupTemplate, Name: "基础配置", Type: models.AdminSettingTypeCheckbox, Field: "templateBasic", Value: `{"isFreezeOrder": true, "isFreezeWithdraw": true}`, Data: `[{"label": "禁用账户禁止下单", "value": "isFreezeOrder"}, {"label": "禁用账户禁止提现", "value": "isFreezeWithdraw"}]`},
		{AdminId: 1, GroupId: models.AdminSettingGroupTemplate, Name: "登录配置", Type: models.AdminSettingTypeCheckbox, Field: "templateLogin", Value: `{"showVerify": true, "showRegister": true}`, Data: `[{"label": "是否显示验证码", "value": "showVerify"}, {"label": "是否显示注册按钮", "value": "showRegister"}]`},
		{AdminId: 1, GroupId: models.AdminSettingGroupTemplate, Name: "注册配置", Type: models.AdminSettingTypeCheckbox, Field: "templateRegister", Value: `{"showVerify": true, "showCmfPass": false, "showSecurityPass": false, "showTelephone": false, "showEmail": false, "isInvite": false, "closeRegister": false}`, Data: `[{"label": "是否显示验证码", "value": "showVerify"}, {"label": "是否显示确认密码", "value": "showCmfPassword"}, {"label": "是否显示安全密码", "value": "showSecurityPassword"}, {"label": "是否显示手机号码", "value": "showTelephone"}, {"label": "是否显示电子邮箱", "value": "showEmail"}, {"label": "是否必须邀请码", "value": "isInvite"}, {"label": "是否关闭注册", "value": "closeRegister"}]`},
		{AdminId: 1, GroupId: models.AdminSettingGroupTemplate, Name: "切换语言配置", Type: models.AdminSettingTypeCheckbox, Field: "templateLang", Value: `{"showLogin": true, "showRegister": true, "showHome": true}`, Data: `[{"label": "登录是否显示", "value": "showLogin"}, {"label": "注册是否显示", "value": "showRegister"}, {"label": "是否显示主页", "value": "showHome"}]`},
		{AdminId: 1, GroupId: models.AdminSettingGroupTemplate, Name: "在线客服配置", Type: models.AdminSettingTypeCheckbox, Field: "templateOnline", Value: `{"showLogin": true, "showRegister": true, "showHome": true, "depositLink": false, "withdrawLink": false}`, Data: `[{"label": "登录是否显示", "value": "showLogin"}, {"label": "注册是否显示", "value": "showRegister"}, {"label": "首页是否显示", "value": "showHome"}, {"label": "充值跳转客服", "value": "linkDeposit"}, {"label": "提现跳转客服", "value": "linkWithdraw"}]`},
		{AdminId: 1, GroupId: models.AdminSettingGroupTemplate, Name: "钱包配置", Type: models.AdminSettingTypeCheckbox, Field: "templateWallet", Value: `{"showSecurityPass": true, "showDelete": true, "showUpdate": true, "showNumber": true}`, Data: `[{"label": "是否输入安全密码", "value": "showSecurityPass"}, {"label": "是否显示更新", "value": "showUpdate"}, {"label": "是否显示删除", "value": "showDelete"}, {"label": "是否显示卡号", "value": "showNumber"}]`},
	}
}
