package database

import (
	"basic/models"
)

// SystemTranslateInit 系统翻译初始化
func SystemTranslateInit() []*models.Translate {
	return []*models.Translate{
		//	基础返回消息翻译
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "验证参数不能为空", Field: "required", Value: "参数不能为空"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "验证参数min", Field: "min", Value: "参数最小值为"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "验证参数max", Field: "max", Value: "参数最大值为"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "验证参数oneof", Field: "oneof", Value: "范围不匹配"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "验证参数大于", Field: "gt", Value: "必须大于"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "验证参数大于等于", Field: "gte", Value: "必须大于等于"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "未设置安全密钥", Field: "notSecurityKey", Value: "未设置安全密钥, 请前往设置..."},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "参数不正确", Field: "incorrectFormat", Value: "格式不正确, 检查当前格式~"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "验证码不正确", Field: "incorrectCode", Value: "验证码不正确"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "旧密码不正确", Field: "TheOldPasswordIsIncorrect", Value: "旧密码不正确"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "旧安全密钥不正确", Field: "TheOldSecurityKeyIsIncorrect", Value: "旧安全密钥不正确"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "账号或密码不正确", Field: "accountOrPasswordIncorrect", Value: "账号或密码不正确"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "安全密钥不能为空", Field: "securityBeEmpty", Value: "安全密钥不能为空"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "安全密钥不正确", Field: "securityKeyIncorrect", Value: "安全密钥不正确"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "手机号码不能为空", Field: "telephoneBeEmpty", Value: "手机号码不能为空"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "邮箱不能为空", Field: "emailBeEmpty", Value: "邮箱不能为空"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "邀请码不存在", Field: "inviteBeEmpty", Value: "邀请码不存在"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "暂时不能注册", Field: "notRegister", Value: "暂时不能注册"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "账单类型不正确", Field: "wrongBillType", Value: "账单类型不正确"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "用户名不存在", Field: "usernameNotFound", Value: "用户名不存在"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "支付方式不存在", Field: "paymentNotFound", Value: "支付方式不存在"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "余额不足", Field: "insufficientBalance", Value: "余额不足"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "未绑定卡片", Field: "accountBeEmpty", Value: "未绑定卡片"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "超出绑定限制", Field: "cardAdditionLimitExceeded", Value: "超出绑定限制"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "超出提现次数", Field: "exceededNumberOfWithdrawals", Value: "提款次数超出"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "金额范围不匹配", Field: "amountBetweenMismatch", Value: "金额范围不匹配"},

		//	钱包账单翻译
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "账单类型充值", Field: "walletBillTypeDeposit", Value: "余额充值"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "账单类型提现", Field: "walletBillTypeWithdraw", Value: "余额提现"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "账单类型资产充值", Field: "walletBillTypeAssetsDeposit", Value: "资产充值"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "账单类型资产提现", Field: "walletBillTypeAssetsWithdraw", Value: "资产提现"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "账单类型购买产品", Field: "walletBillTypeBuyProduct", Value: "购买产品"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "账单类型购买等级", Field: "walletBillTypeBuyLevel", Value: "购买等级"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "账单类型收益", Field: "walletBillTypeEarnings", Value: "收益"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "账单类型奖励", Field: "walletBillTypeAward", Value: "奖励"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "账单类型资产购买产品", Field: "walletBillTypeAssetsBuyProduct", Value: "资产购买产品"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "账单类型资产收益", Field: "walletBillTypeAssetsEarnings", Value: "资产收益"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "账单类型资产奖励", Field: "walletBillTypeAssetsAward", Value: "资产奖励"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "账单类型注册奖励", Field: "walletBillTypeRegisterAward", Value: "注册奖励"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "账单类型邀请奖励", Field: "walletBillTypeShareAward", Value: "邀请奖励"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "账单类型系统充值", Field: "walletBillTypeSystemDeposit", Value: "余额系统充值"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "账单类型资产系统充值", Field: "walletBillTypeSystemAssetsDeposit", Value: "资产系统充值"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "账单类型系统扣款", Field: "walletBillTypeSystemWithdraw", Value: "余额系统扣款"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "账单类型资产系统扣款", Field: "walletBillTypeSystemAssetsWithdraw", Value: "资产系统扣款"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "账单类型团队收益", Field: "walletBillTypeTeamEarnings", Value: "团队收益"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "账单类型团队资产收益", Field: "walletBillTypeTeamAssetsEarnings", Value: "团队资产收益"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "账单类型资金提现拒绝", Field: "walletBillTypeWithdrawRefuse", Value: "资金提现拒绝"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "账单类型资产提现拒绝", Field: "walletBillTypeAssetsWithdrawRefuse", Value: "资产提现拒绝"},

		//	数据翻译
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "level1标题", Field: "level1Label", Value: "VIP1"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "level2标题", Field: "level2Label", Value: "VIP2"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "level3标题", Field: "level3Label", Value: "VIP3"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "level4标题", Field: "level4Label", Value: "VIP4"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "level5标题", Field: "level5Label", Value: "VIP5"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "level1详情", Field: "level1Desc", Value: "VIP等级介绍详情信息..."},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "level2详情", Field: "level2Desc", Value: "VIP等级介绍详情信息..."},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "level3详情", Field: "level3Desc", Value: "VIP等级介绍详情信息..."},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "level4详情", Field: "level4Desc", Value: "VIP等级介绍详情信息..."},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "level5详情", Field: "level5Desc", Value: "VIP等级介绍详情信息..."},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "储蓄卡", Field: "DebitCard", Value: "储蓄卡"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "美国银行", Field: "BankOfAmerica", Value: "美国银行"},

		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "储蓄卡(资金提现)", Field: "bankFundsWithdraw", Value: "储蓄卡[资金提现]"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "储蓄卡(资产提现)", Field: "bankAssetsWithdraw", Value: "储蓄卡[资产提现]"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "数字货币(资金提现)", Field: "digitalFundsWithdraw", Value: "数字货币[资金提现]"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "数字货币(资产提现)", Field: "digitalAssetsWithdraw", Value: "数字货币[资产提现]"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "储蓄卡(资金充值)", Field: "bankFundsDeposit", Value: "储蓄卡[资金充值]"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "储蓄卡(资产充值)", Field: "bankAssetsDeposit", Value: "储蓄卡[资产充值]"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "数字货币(资金充值)", Field: "digitalFundsDeposit", Value: "数字货币[资金充值]"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "数字货币(资产充值)", Field: "digitalAssetsDeposit", Value: "数字货币[资产充值]"},

		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "充值提示详情", Field: "depositDesc", Value: "充值注意事项"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "提现提示详情", Field: "withdrawDesc", Value: "提现注意事项"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "站点介绍", Field: "siteIntroduce", Value: "站点介绍"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "站点通知", Field: "siteAnnouncement", Value: "站点通知"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "关于我们", Field: "aboutUs", Value: "关于我们"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "平台服务", Field: "siteService", Value: "平台服务"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "联系我们", Field: "contactUs", Value: "联系我们"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "社区", Field: "social", Value: "社区"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "关于我们标题", Field: "aboutUsLabel", Value: "关于我们"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "关于我们详情", Field: "aboutUsDesc", Value: `<pre><span style="font-family: Roboto, -apple-system, Avenir, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; white-space-collapse: collapse;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">关于我们</font></font></span><div style="font-family: Roboto, -apple-system, Avenir, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; white-space-collapse: collapse;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">欢迎来到创新与卓越相遇的地方！ 我们是一家先锋科技企业，致力于突破技术界限并为客户提供卓越的解决方案。 我们的承诺不仅仅是创新； 这是关于了解客户需求并承担社会责任。</font></font></div><div style="font-family: Roboto, -apple-system, Avenir, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; white-space-collapse: collapse;"><br></div><div style="font-family: Roboto, -apple-system, Avenir, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; white-space-collapse: collapse;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">我们的使命和核心价值观</font></font></div><div style="font-family: Roboto, -apple-system, Avenir, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; white-space-collapse: collapse;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">在[公司名称]，我们的使命是通过创新为未来铺平道路。 我们的核心价值观决定了我们的成功：</font></font></div><div style="font-family: Roboto, -apple-system, Avenir, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; white-space-collapse: collapse;"><br></div><div style="font-family: Roboto, -apple-system, Avenir, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; white-space-collapse: collapse;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">技术创新：不断探索和采用前沿技术，提供最先进的解决方案和服务。</font></font></div><div style="font-family: Roboto, -apple-system, Avenir, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; white-space-collapse: collapse;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">以客户为中心的方法：通过提供满足客户独特需求的高质量定制服务来优先考虑客户的成功。</font></font></div><div style="font-family: Roboto, -apple-system, Avenir, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; white-space-collapse: collapse;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">协作团队合作：我们的团队由顶级专业人士组成，我们相信协作是成功的关键，他们不断协作以实现共同成功。</font></font></div><div style="font-family: Roboto, -apple-system, Avenir, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; white-space-collapse: collapse;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">社会责任：作为企业责任的一部分，我们积极支持可持续发展努力，为社会进步做出贡献。</font></font></div><div style="font-family: Roboto, -apple-system, Avenir, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; white-space-collapse: collapse;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">我们的服务范围</font></font></div><div style="font-family: Roboto, -apple-system, Avenir, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; white-space-collapse: collapse;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">我们提供跨多个领域的全面服务：</font></font></div><div style="font-family: Roboto, -apple-system, Avenir, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; white-space-collapse: collapse;"><br></div><div style="font-family: Roboto, -apple-system, Avenir, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; white-space-collapse: collapse;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">软件开发与 工程：利用最新的软件开发技术，我们提供高效、可靠和定制的软件解决方案。</font></font></div><div style="font-family: Roboto, -apple-system, Avenir, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; white-space-collapse: collapse;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">人工智能与 数据分析：专注于人工智能和数据分析，利用洞察和智能技术提供定制化解决方案。</font></font></div><div style="font-family: Roboto, -apple-system, Avenir, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; white-space-collapse: collapse;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">物联网 (IoT) 和 未来技术：我们致力于推进物联网和未来技术，创造智能解决方案和创新产品。</font></font></div><div style="font-family: Roboto, -apple-system, Avenir, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; white-space-collapse: collapse;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">数字化转型服务：协助企业数字化转型，利用技术提高效率、降低成本、创造更多商业价值。</font></font></div><div style="font-family: Roboto, -apple-system, Avenir, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; white-space-collapse: collapse;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">客户关系</font></font></div><div style="font-family: Roboto, -apple-system, Avenir, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; white-space-collapse: collapse;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">与客户建立持久的合作伙伴关系是我们的首要任务。 我们用心倾听他们的需求，提供个性化的解决方案，并提供持续的支持以推动他们的持续增长。 积极寻求并纳入客户反馈可确保我们提供最优质的服务和技术支持。</font></font></div><div style="font-family: Roboto, -apple-system, Avenir, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; white-space-collapse: collapse;"><br></div><div style="font-family: Roboto, -apple-system, Avenir, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; white-space-collapse: collapse;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">社会责任承诺</font></font></div><div style="font-family: Roboto, -apple-system, Avenir, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; white-space-collapse: collapse;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">我们不仅仅是一家科技公司； 我们是社会责任的管家。 参与社区活动、支持环境保护和支持社会事业是我们致力于社会进步和可持续发展的重要组成部分。</font></font></div><div style="font-family: Roboto, -apple-system, Avenir, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; white-space-collapse: collapse;"><br></div><div style="font-family: Roboto, -apple-system, Avenir, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; white-space-collapse: collapse;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">与我们合作</font></font></div><div style="font-family: Roboto, -apple-system, Avenir, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; white-space-collapse: collapse;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">无论您的业务阶段或需求如何，我们都致力于成为您值得信赖的合作伙伴，提供最佳的技术解决方案。 如果您想进一步探索我们的服务或与我们合作，请随时与我们联系。</font></font></div><div style="font-family: Roboto, -apple-system, Avenir, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; white-space-collapse: collapse;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">我们的创新方法</font></font></div><div style="font-family: Roboto, -apple-system, Avenir, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; white-space-collapse: collapse;"><br></div><div style="font-family: Roboto, -apple-system, Avenir, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; white-space-collapse: collapse;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">创新不仅仅是一个流行词，而是一个新词。 这是支撑我们所做一切的理念。 这是我们运营的基石。 对创新的不懈追求促使我们不断探索新技术和新方法，确保我们保持领先优势。 我们大力投资研发，培育鼓励创造力、实验和创新思维的文化。</font></font></div><div style="font-family: Roboto, -apple-system, Avenir, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; white-space-collapse: collapse;"><br></div><div style="font-family: Roboto, -apple-system, Avenir, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; white-space-collapse: collapse;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">我们成功背后的团队</font></font></div><div style="font-family: Roboto, -apple-system, Avenir, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; white-space-collapse: collapse;"><br></div><div style="font-family: Roboto, -apple-system, Avenir, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; white-space-collapse: collapse;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">我们的成功归功于一支多元化且才华横溢的团队。 他们由行业专家、远见卓识者和具有前瞻性思维的个人组成，他们在挑战中不断成长，并无缝协作，提供突破性的解决方案。 我们重视多样性、包容性和持续学习，创造一个促进增长和创新的环境。</font></font></div><div style="font-family: Roboto, -apple-system, Avenir, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; white-space-collapse: collapse;"><br></div><div style="font-family: Roboto, -apple-system, Avenir, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; white-space-collapse: collapse;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">行业认可和成就</font></font></div><div style="font-family: Roboto, -apple-system, Avenir, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; white-space-collapse: collapse;"><br></div><div style="font-family: Roboto, -apple-system, Avenir, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; white-space-collapse: collapse;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">我们对卓越和创新的承诺赢得了业界的认可。 我们对我们的成就感到自豪，不仅将它们视为里程碑，而且将其视为进一步前进的灵感。 我们的业绩记录意义重大，反映出我们致力于提供超出预期的成果。</font></font></div><div style="font-family: Roboto, -apple-system, Avenir, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; white-space-collapse: collapse;"><br></div><div style="font-family: Roboto, -apple-system, Avenir, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; white-space-collapse: collapse;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">道德实践和透明度</font></font></div><div style="font-family: Roboto, -apple-system, Avenir, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; white-space-collapse: collapse;"><br></div><div style="font-family: Roboto, -apple-system, Avenir, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; white-space-collapse: collapse;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">透明度和道德实践构成了我们运营的基石。 我们与客户、合作伙伴和利益相关者保持开放的沟通，确保每次互动中的信任和可靠性。 我们对诚信的承诺指导着我们所有的业务往来。</font></font></div><div style="font-family: Roboto, -apple-system, Avenir, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; white-space-collapse: collapse;"><br></div><div style="font-family: Roboto, -apple-system, Avenir, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; white-space-collapse: collapse;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">可持续发展和环境意识</font></font></div><div style="font-family: Roboto, -apple-system, Avenir, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; white-space-collapse: collapse;"><br></div><div style="font-family: Roboto, -apple-system, Avenir, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; white-space-collapse: collapse;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">作为一个负责任的企业实体，我们在运营的各个方面都优先考虑可持续发展。 我们将环保实践融入我们的流程中，努力最大限度地减少我们的环境足迹。 此外，我们积极支持促进环境保护和生态意识的举措。</font></font></div><div style="font-family: Roboto, -apple-system, Avenir, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; white-space-collapse: collapse;"><br></div><div style="font-family: Roboto, -apple-system, Avenir, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; white-space-collapse: collapse;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">拥抱变革，共创美好未来</font></font></div><div style="font-family: Roboto, -apple-system, Avenir, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; white-space-collapse: collapse;"><br></div><div style="font-family: Roboto, -apple-system, Avenir, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; white-space-collapse: collapse;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">我们将变革视为进步的催化剂。 我们迅速适应不断发展的技术格局，预见趋势，并为我们自己和我们的客户做好迎接未来挑战和机遇的准备。</font></font></div><div style="font-family: Roboto, -apple-system, Avenir, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; white-space-collapse: collapse;"><br></div><div style="text-align: left; font-family: Roboto, -apple-system, Avenir, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; white-space-collapse: collapse;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">加入我们的创新之旅</font></font></div></pre>`},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "服务协议标题", Field: "serviceAgreementLabel", Value: "服务协议"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "服务协议详情", Field: "serviceAgreementDesc", Value: "服务描述\n平台同意按照本协议的条款和条件向用户提供以下服务：\n*   账户管理 - 用户可以在平台上创建和管理个人交易账户，包括存储、兑换和交易数字货币。\n*   交易服务 - 平台提供数字货币交易服务，包括买卖订单管理、市场信息提供和交易执行。\n*   安全与合规 - 平台致力于提供安全的交易环境，并遵守相关的法律法规。\n*   客户支持 - 用户可以通过客户支持获取交易相关的帮助和咨询。\n用户责任\n*   账户安全 - 用户负责保护其账户信息的安全，包括用户名和密码。\n*   合规操作 - 用户同意遵守所有适用的法律、法规和平台的规则。\n*   风险认知 - 用户理解并同意，数字货币交易存在市场风险，包括但不限于价格波动、技术问题和法律风险。\n风险披露\n用户明白，数字货币交易涉及高风险，可能导致部分或全部资金的损失。用户应根据自己的财务状况和风险承受能力进行交易。\n知识产权\n平台的所有内容和技术，包括但不限于软件、界面设计、商标和版权均属于平台或其授权人所有。\n免责声明\n平台不对由于系统故障、网络问题或其他不可抗力因素导致的服务中断或交易问题承担责任。\n修改和终止\n平台保留随时修改本协议或服务内容的权利，并会提前通知用户。用户继续使用服务即表示接受修改后的协议。\n适用法律和争端解决\n本协议的解释和执行适用 。任何由本协议引起的争端应通过友好协商解决，如协商不成，可提交法院诉讼解决。"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "隐私协议标题", Field: "privacyAgreementLabel", Value: "隐私协议"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "隐私协议详情", Field: "privacyAgreementDesc", Value: `<div style="text-align: left;"><span style="font-family: Roboto, -apple-system, Avenir, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">尊敬的用户欢迎使用 我们的产品和服务。 我们深知您对个人信息安全和隐私的重视，我们将尽力保护您个人信息的安全，并遵循以下隐私政策： 收集信息的目的：我们收集您的个人信息 为了更好地为您提供服务，提升用户体验，保证产品和服务的安全。 我们只会收集必要的信息，绝不会超出声明目的使用您的个人信息。 收集的信息类型：我们可能收集的信息类型包括但不限于：姓名、电子邮件地址、联系信息、IP地址、设备信息、浏览器类型等信息使用和共享：我们只会使用您的个人信息 在提供服务和提高产品质量的范围内。 除非获得您的同意或法律法规要求，我们不会向任何第三方出售、出租或分享您的个人信息。 信息安全：我们采取了一系列安全措施来保护您的个人信息，包括但不限于加密技术、访问控制、安全审计等。我们将尽力确保您的信息安全，不被未经授权的访问、使用 或披露。 用户权利：您有权查询、更正、删除个人信息。 如果您对我们收集的个人信息有任何疑问或需要行使相关权利，请随时联系我们的客服团队。 隐私政策的变更：随着我们的产品和服务的发展，我们的隐私政策可能会不时更新。 我们将在网站上发布任何政策变更，并根据适用法律的要求向您提供通知。 接受条款：使用我们的产品和服务，即表示您同意本隐私政策的条款和条件。 联系我们：如果您对我们的隐私政策有任何疑问或建议，请随时联系我们的隐私团队。 感谢您对我们的信任，我们将继续努力确保您的信息安全和隐私</font></font></span></div>`},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "帮助中心1标题", Field: "helpers1Label", Value: "重置密码"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "帮助中心1详情", Field: "helpers1Desc", Value: "如果您忘记了密码，可以轻松重置。请在登录页面点击“忘记密码？”链接，然后输入您的注册电子邮件地址。我们将发送一封包含重置密码指令的电子邮件给您。遵循邮件中的指示，您就可以设置新密码。为了保证账户安全，请确保您的新密码足够复杂，且不与其他网站共享相同密码。如果在重置密码过程中遇到任何问题，欢迎联系我们的客户支持团队获取帮助。"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "帮助中心2标题", Field: "helpers2Label", Value: "安全建议"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "帮助中心2详情", Field: "helpers2Desc", Value: "为了保护您的账户安全，我们建议您采取以下措施：首先，使用强密码，结合大写字母、小写字母、数字和特殊符号。其次，定期更换密码，避免使用相同的密码登录不同网站。此外，启用两因素认证（2FA）增加额外的安全层。请勿在公共计算机或不安全的网络环境中登录账户，并始终保持您的个人信息和联系方式更新。最后，警惕任何可疑的邮件或信息，避免点击不明链接或分享敏感信息。"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "帮助中心3标题", Field: "helpers3Label", Value: "取消订阅"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "帮助中心3详情", Field: "helpers3Desc", Value: "取消订阅非常简单。登录您的账户后，前往账户设置 页面，在那里您会找到“订阅管理”选项。选择您想要取消的服务，并点击“取消订阅”按钮。根据您的订阅类型，可能会有一段提前通知期。请注意，取消订阅可能会影响到您享受的某些服务或优惠。如果您在取消订阅过程中遇到任何问题或需要进一步的帮助，欢迎随时联系我们的客户服务团队。"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "帮助中心4标题", Field: "helpers4Label", Value: "支付方式"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "帮助中心4详情", Field: "helpers4Desc", Value: "为了方便用户，我们支持多种支付方式。您可以使用信用卡（Visa, MasterCard, American Express等）、借记卡、电子钱包（如PayPal, Apple Pay等）以及银行转账等方式进行支付。所有支付过程都是经过加密的，确保您的交易信息安全。请注意，根据您所在的地区，可用的支付方式可能会有所不同。如果您在支付过程中遇到任何问题，或者需要了解更多关于支付选项的信息，请联系我们的客户支持团队。"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "帮助中心5标题", Field: "helpers5Label", Value: "退货政策"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "帮助中心5详情", Field: "helpers5Desc", Value: "我们承诺提供满意的退货政策。如果您对购买的产品不满意，可以在收到货物后30天内申请退货。要开始退货流程，请登录您的账户并前往“订单历史”页面，选择相应的订单并点击“申请退货”。请确保退回的商品处于未使用状态，并包含所有原包装和附件。退货处理完成后，我们将退还您的支付金额，退款通常在5至10个工作日内处理完毕。如果您在退货过程中需要任何帮助，请随时联系我们的客户服务"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "帮助中心6标题", Field: "helpers6Label", Value: "追踪订单"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "帮助中心6详情", Field: "helpers6Desc", Value: "在您的订单被发货后，您将通过电子邮件收到一个包含追踪链接的发货通知。点击该链接，您可以查看订单的最新运输状态和预计送达时间。此外，您也可以直接在我们的网站上通过“我的订单”部分追踪订单状态。如果您对订单的运输状态有任何疑问或需要帮助，请联系我们的客户服务团队。"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "帮助中心7标题", Field: "helpers7Label", Value: "产品期限"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "帮助中心7详情", Field: "helpers7Desc", Value: "我们的产品享有一定期限的保修服务，确保您在使用过程中得到必要的支持。保修期限通常从购买日期起算，具体时长取决于产品类型。保修内容通常包括制造缺陷和材料问题。在保修期内，如果产品出现合格的保修问题，我们将提供免费修理或更换服务。请注意，保修不包括因误用、正常磨损或未经授权的维修造成的损坏。详细的保修条款和条件请参见我们的产品保修政策，或联系我们的客户服务团队获取更多信息。"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "平台服务1标题", Field: "service1Label", Value: "产品服务"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "平台服务1详情", Field: "service1Desc", Value: "欢迎来到我们的交易所平台！我们是一家致力于为您提供安全、高效、多样化的交易体验的领先交易平台。无论您是初学者还是经验丰富的交易者，我们都为您提供了丰富的产品和服务，以满足您的需求。<br />我们的产品特点：<br />多样化的交易对: 我们支持多种数字资产交易对，涵盖主流加密货币以及新兴数字资产，让您可以灵活选择交易组合。<br />安全保障: 我们采取严格的安全措施，包括多重身份验证、冷热钱包存储体系等，保障您的资产安全。<br />高效的交易执行: 我们的平台配备高性能的交易引擎，保证交易执行速度和效率，让您能够快速响应市场变化。<br />用户友好的界面: 我们的界面简洁直观，适合各种水平的交易者使用，同时也提供了专业级别的图表和工具，满足有更高要求的用户。<br />教育资源和客户支持: 我们提供广泛的教育资源，包括文章、视频和在线课程，帮助您了解市场动态和交易策略。此外，我们的客户支持团队全天候为您提供支持。<br /><br />我们的服务承诺：<br />透明度与合规性: 我们遵循严格的法规标准，保障交易过程的透明度和合规性。<br />持续创新与发展: 我们致力于不断提升平台功能和服务，引入新的技术和工具，以满足市场不断变化的需求。<br />社区参与与奖励: 我们鼓励社区参与，通过奖励计划回馈我们的忠实用户。<br />无论您是寻求快速交易、投资多样化数字资产，还是寻找一个安全可靠的交易所平台，我们都将竭诚为您提供最优质的服务和支持。<br />加入我们，开始您的交易之旅吧！"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "平台服务2标题", Field: "service2Label", Value: "基础方案"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "平台服务2详情", Field: "service2Desc", Value: "注册和账户管理<br />浏览市场和实时数据<br />限制性的交易功能<br />专业方案 - $9.99/月：<br />全面的交易功能，包括买卖、存款和提款<br />高级图表和分析工具<br />客户支持优先服务<br />额外的教育资源和市场报告<br />企业方案 - 定制报价：<br />适用于机构和专业交易者<br />定制化的解决方案<br />安全审计和额外的安全措施<br />专属的客户经理和支持团队<br />价格策略说明：<br />弹性定价: 我们提供多种价格选择，满足不同用户群体的需求。用户可以根据其需求和预算选择适合自己的方案。<br />试用期: 对于新用户，我们提供免费试用期或者特定功能的试用，让用户可以在付费前体验我们的服务。<br />优惠和折扣: 定期推出促销活动、折扣和特惠套餐，以回馈现有用户并吸引新用户。<br />定期支付: 客户可以选择按月或按年支付，按年支付的用户可以享受一定的折扣优惠。<br />定价透明度与承诺：<br />我们承诺定价透明，没有隐藏费用或附加费用。所有价格均明确列出，让用户清楚了解他们所支付的服务内容。我们也欢迎用户反馈和建议，以不断优化我们的定价策略，以更好地满足用户需求。"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "平台服务3标题", Field: "service3Label", Value: "新产品介绍"},
		{AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "平台服务3详情", Field: "service3Desc", Value: "在数字资产市场的不断演变和增长中，我们引以为傲地推出了全新的「数字资产投资组合优化工具」，旨在帮助投资者最大化其投资回报并降低风险。<br />主要特点：<br />智能投资组合优化：<br />利用先进的算法和数据分析，我们的工具能够帮助用户构建最优的数字资产投资组合，考虑到风险和收益的平衡。<br />动态资产配置：<br />根据市场实时数据和用户偏好，工具能够动态调整投资组合，以应对市场波动和变化，最大程度地优化投资组合表现。<br />风险管理与模拟测试：<br />提供多种风险管理工具，让用户能够对不同的投资方案进行模拟测试，了解可能的风险和回报情况，做出更明智的投资决策。<br />个性化建议与报告：<br />提供个性化的投资建议和定期报告，帮助用户跟踪投资组合的表现，并根据实时数据做出调整。<br />如何使用我们的产品：<br />注册账户：<br />快速注册账户并登录我们的平台。<br />输入投资偏好：<br />根据您的投资目标、风险承受能力和偏好，输入相关信息。<br />获取优化建议：<br />根据您提供的信息，工具将生成最佳的数字资产投资组合建议。<br />跟踪和调整：<br />定期跟踪投资组合表现，并根据报告的建议调整您的投资策略。<br />我们的承诺：<br />我们的「数字资产投资组合优化工具」旨在为您提供更智能、更高效的投资解决方案。我们致力于提供卓越的用户体验，确保您的投资决策更加明智和可靠。"},

		//	前台翻译使用
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "未添加资产", Field: "notAssets", Value: "未添加资产"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "饼图", Field: "pieChart", Value: "饼图"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "折线图", Field: "lineChart", Value: "折线图"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "全部", Field: "all", Value: "全部"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "前往", Field: "goto", Value: "前往"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "暂无数据", Field: "noData", Value: "暂无数据"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "注册时间", Field: "createdTime", Value: "注册时间"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "确定操作标题", Field: "isExecute", Value: "您是否确定执行当前操作?"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "确定购买", Field: "isBuy", Value: "您是否确定购买"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "货币单位", Field: "currency", Value: "$"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "充值", Field: "deposit", Value: "充值"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "提现", Field: "withdraw", Value: "提现"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "首页", Field: "home", Value: "首页"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "行情", Field: "markets", Value: "市场"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "合约", Field: "contract", Value: "合约"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "期货", Field: "futures", Value: "期货"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "我的", Field: "user", Value: "我的"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "数字货币", Field: "digitalMarkets", Value: "数字货币"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "外汇市场", Field: "forexMarkets", Value: "外汇市场"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "期货市场", Field: "futuresMarkets", Value: "期货市场"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "钱包管理", Field: "walletManage", Value: "钱包管理"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "团队管理", Field: "teamManage", Value: "团队管理"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "服务设置", Field: "serviceManage", Value: "服务设置"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "卡片管理", Field: "accountManage", Value: "卡片管理"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "我的钱包", Field: "myWallet", Value: "我的钱包"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "我的资产", Field: "myAssets", Value: "我的资产"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "邀请好友", Field: "inviteFriends", Value: "邀请好友"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "我的团队", Field: "myTeam", Value: "我的团队"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "团队收益", Field: "teamEarnings", Value: "团队收益"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "团队成员", Field: "teamMember", Value: "团队成员"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "会员中心", Field: "memberVip", Value: "会员中心"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "实名认证", Field: "realAuth", Value: "实名认证"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "帮助中心", Field: "helpers", Value: "帮助中心"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "个人设置", Field: "settings", Value: "个人设置"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "下载中心", Field: "download", Value: "下载中心"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "下载副标题", Field: "downloadSmall", Value: "使用手机版本能更好的体验服务~"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "邀请好友副标题", Field: "inviteFriendsSmall", Value: "邀请您的好友一起Happy, 同时能领取到惊喜收益。"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "会员中心副标题", Field: "memberVipSmall", Value: "升级成为尊贵的会员用户, 同时享受各种平台优惠服务~"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "会员中心标题", Field: "memberVipTitle", Value: "选择您的会员计划"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "登录", Field: "login", Value: "登录"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "忘记密码", Field: "forgotPassword", Value: "忘记密码?"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "登录副标题", Field: "loginSmall", Value: "登录您的账号, 开启旅程～"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "未注册去登录", Field: "toRegister", Value: "还没有账号, 去注册!"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "注册", Field: "register", Value: "注册"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "注册副标题", Field: "registerSmall", Value: "创建您的账户, 开启旅程~"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "已有账户去登录", Field: "toLogin", Value: "已有账户, 现在去登录!"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "退出登录", Field: "logout", Value: "退出登录"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "退出登录副标题", Field: "logoutSmall", Value: "您确定要退出登录吗?"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "有什么能帮上您的吗", Field: "helperYou", Value: "你好, 有什么能帮上您的吗?"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "24小时在线服务", Field: "24hoursOnline", Value: "24小时在线服务"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "更多", Field: "more", Value: "更多"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "查询", Field: "search", Value: "查询"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "提交", Field: "submit", Value: "提交"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "重新提交", Field: "reSubmit", Value: "重新提交"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "完成", Field: "complete", Value: "完成"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "审核", Field: "pending", Value: "审核"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "拒绝", Field: "refuse", Value: "拒绝"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "筛选", Field: "filter", Value: "筛选"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "类型", Field: "type", Value: "类型"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "时间范围", Field: "betweenTime", Value: "时间范围"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "余额", Field: "balance", Value: "余额"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "充值金额", Field: "depositAmount", Value: "充值金额"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "提现金额", Field: "withdrawAmount", Value: "提现金额"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "可用金额", Field: "availableAmount", Value: "可用金额"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "充值凭证", Field: "depositProof", Value: "充值凭证"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "提现账户", Field: "withdrawAccount", Value: "提现账户"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "未绑定提现账户", Field: "notBindWithdrawAccount", Value: "未绑定提现账户"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "充值帐户", Field: "depositAccount", Value: "充值帐户"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "账户信息", Field: "depositAccountInfo", Value: "账户信息"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "总资产", Field: "totalAssets", Value: "总资产"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "资产分布", Field: "assetsBlock", Value: "资产分布"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "资产", Field: "assets", Value: "资产"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "取消", Field: "cancel", Value: "取消"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "确定", Field: "confirm", Value: "确定"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "删除", Field: "delete", Value: "删除"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "删除确认标题", Field: "deleteLabel", Value: "删除确定"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "是否确定删除当前记录", Field: "deleteRecord", Value: "是否确定删除当前记录?"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "新增", Field: "create", Value: "新增"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "编辑", Field: "edit", Value: "编辑"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "详情", Field: "desc", Value: "详情"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "查看", Field: "views", Value: "查看"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "复制", Field: "copy", Value: "复制"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "复制成功", Field: "copySuccess", Value: "复制成功"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "购买", Field: "buy", Value: "购买"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "立即购买", Field: "nowBuy", Value: "立即购买"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "已购买", Field: "purchased", Value: "已购买"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "钱包交易记录", Field: "transactions", Value: "交易记录"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "钱包账单明细", Field: "billDetails", Value: "账单明细"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "提交成功", Field: "submittedSuccess", Value: "提交成功"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "账号", Field: "username", Value: "账号"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "验证码", Field: "code", Value: "验证码"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "旧密码", Field: "oldPassword", Value: "旧密码"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "新密码", Field: "newPassword", Value: "新密码(如果未设置请为空)"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "确认密码", Field: "cmfPassword", Value: "确认密码"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "确认安全密码", Field: "cmfSecretKey", Value: "确认安全密码"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "两次密码不一样", Field: "twoPasswordsAreDifferent", Value: "两次密码不一样"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "两次密钥不一样", Field: "twoSecretKeyAreDifferent", Value: "两次密钥不一样"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "请输入密钥", Field: "enterSecretKey", Value: "请输入密钥"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "邀请码", Field: "inviteCode", Value: "邀请码"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "密码", Field: "password", Value: "密码"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "密码副标题", Field: "passwordSmall", Value: "编辑登录密码, 确保您的账户安全。"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "安全密码", Field: "secretKey", Value: "安全密码"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "安全密码副标题", Field: "secretKeySmall", Value: "编辑安全密钥, 确保您的账户资金安全。"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "邮箱", Field: "email", Value: "邮箱地址"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "邮箱副标题", Field: "emailSmall", Value: "绑定您的邮箱~"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "手机号码", Field: "telephone", Value: "手机号码"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "手机号码副标题", Field: "telephoneSmall", Value: "绑定您的手机号码~"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "头像", Field: "avatar", Value: "头像"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "头像副标题", Field: "avatarSmall", Value: "编辑您的头像, 更能体现您的气质~"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "昵称", Field: "nickname", Value: "昵称"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "昵称副标题", Field: "nicknameSmall", Value: "编辑自己昵称, 使用个性化昵称~"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "性别", Field: "sex", Value: "性别"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "男", Field: "male", Value: "男"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "女", Field: "female", Value: "女"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "未知", Field: "unknown", Value: "未知"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "性别副标题", Field: "sexSmall", Value: "编辑性别~"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "生日", Field: "birthday", Value: "生日"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "生日副标题", Field: "birthdaySmall", Value: "设置您的生日, 让我们给你一份惊喜~"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "个性签名", Field: "personalSignature", Value: "个性签名"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "个性签名副标题", Field: "personalSignatureSmall", Value: "让更多用户知道您的兴趣爱好~"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "证件名称", Field: "idName", Value: "证件名称"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "证件号码", Field: "idNumber", Value: "证件号码"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "证件照片", Field: "idPhoto", Value: "证件照片"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "证件正面", Field: "idPhoto1", Value: "证件照正面"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "证件反面", Field: "idPhoto2", Value: "证件照反面"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "手持证件", Field: "idPhoto3", Value: "手持证件照"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "详细地址", Field: "address", Value: "详细地址"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "银行名称", Field: "bankName", Value: "银行名称"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "归属姓名", Field: "ownerName", Value: "真实姓名"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "银行卡号", Field: "bankNumber", Value: "银行卡号"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "银行地址", Field: "bankAddress", Value: "银行地址"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "网络名称", Field: "digitalNetwork", Value: "数字网络"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "数字地址", Field: "digitalAddress", Value: "数字地址"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "设置", Field: "setting", Value: "设置"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "个人设置", Field: "personalSetting", Value: "个人设置"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "修改登录密码", Field: "updatePassword", Value: "登录密码"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "修改安全密码", Field: "updateSecretKey", Value: "安全密钥"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "绑定邮箱", Field: "bindEmail", Value: "绑定邮箱"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "绑定手机号码", Field: "bindTelephone", Value: "绑定手机号码"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "绑定手机号码副标题", Field: "bindTelephoneSmall", Value: "请输入您的有效电话号码。 我们将向您发送 4 位代码来验证帐户。输入电话号码"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "语言", Field: "language", Value: "语言"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "关于", Field: "about", Value: "关于"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "新的通知", Field: "noticeEnable", Value: "新的通知"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "信用分", Field: "creditScore", Value: "信用分"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "未实名", Field: "alreadyRealName", Value: "未实名"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "实名失败", Field: "notRealName", Value: "验证失败"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "实名审核中", Field: "pendingRealName", Value: "审核中"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "已实名", Field: "realNameFailed", Value: "已实名"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "邀请总数", Field: "inviteNums", Value: "邀请总数"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "今日人数", Field: "todayNums", Value: "今日人数"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "购买总额", Field: "buyAmount", Value: "购买总额"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "今日总额", Field: "todayAmount", Value: "今日总额"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "团队收益", Field: "teamEarnings", Value: "团队收益"},
		{Type: models.TranslateTypeHome, AdminId: models.SuperAdminId, Lang: "zh-CN", Name: "今日收益", Field: "todayEarnings", Value: "今日收益"},
	}
}
