# 项目配置
Basic:
  # 项目名称
  Name: "八戒网络科技"
  # 是否开启Debug
  Debug: true
  # 启动端口
  Port: 3010
  # 后台API接口域名
  AdmDomain: "api.adm.localhost:3010"
  # Header名称
  ServerHeader: "TaoZi"
  # 是否开启子进程模式
  Prefork: false

# Mysql配置
Database:
  # 连接协议
  Network: "tcp"
  # 服务器地址
  Server: "127.0.0.1"
  # 数据库端口
  Port: 3307
  # 数据库用户名
  User: "root"
  # 数据库密码
  Pass: "123456"
  # 数据库名称
  DbName: "basic"

# Redis配置
Redis:
  # 连接协议
  Network: "tcp"
  # 服务器地址
  Server: "127.0.0.1"
  # 端口
  Port: 6380
  # 密码
  Pass: ""
  # 数据库 0-15
  Dbname: 0
  # 连接超时时间
  ConnectTimeout: 30
  # 读取超时时间
  ReadTimeout: 30
  # 写入超时时间
  WriteTimeout: 30
  # 设置最大连接数
  MaxOpenConn: 0
  # 空闲连接超时
  ConnMaxIdleTime: 30
  # 最大空闲连接数
  MaxIdleConn: 0
  # 如果超过最大连接数是否等待
  Wait: false